#spring.application.name=microservice

spring:
  application:
    name: eurekaMicroservice
  security:
    basic:
      enabled: true
    user:
      name: eureka
      password: 123

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # nao deixa o eureka se autoregistrar como cliente
    fetch-registry: false # nao deixar buscar registros de microservice porque sera funcao do GATWAEY
