#spring.application.name=microservice

spring:
  application:
    name: eurekaMicroservice



server:
  port: 8761

eureka:
  client:
    register-with-eureka: false  # nao deixa o eureka se autoregistrar como cliente
    fetch-registry: false # nao deixar buscar registros de microservice porque sera funcao do GATWAEY

