spring:
  application:
    name: mscards  # Define o nome da aplicação como "mscards"

server:
  port: 0  # Configura o servidor para escolher uma porta aleatória disponível, útil para evitar conflitos de porta

# Configuração para inscrição do microserviço no servidor Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Define a URL do servidor Eureka para o registro do microserviço

  instance:
    # Configuração para nomear a instância do microserviço
    # Usa uma combinação do nome da aplicação e um valor aleatório como ID da instância
    # Isso garante que cada instância do serviço tenha um ID único, evitando conflitos
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
